### PR TITLE
UI Improvements in ChatActivity & Others,  + Dark Mode fixes

### PR DESCRIPTION
**Pull request by Mouniraki**
Addresses issue #350.
This PR involves very little changes, only UI-wise, to fix little issues when elements are displayed on screen.

**EDIT: A little issue with how the User profile is fetched for the demo account has also now been fixed.**

### CODE REVIEW

**Review by DeepGreen1 — APPROVED** [review]
Everything seems fine. It could be nice to put those profile images back for the demo :)

**Review by omarelmalki — APPROVED** [review]
Great job on the changes. A few bonus UI changes :
- In QRCodeShow activity, try to reduce the size of the large token and keep either its name or its id (content of the QRCode).

**Comment by Mouniraki** [comment]
> Great job on the changes. A few bonus UI changes :
> 
> * In QRCodeShow activity, try to reduce the size of the large token and keep either its name or its id (content of the QRCode).

Thank you for your review ! Indeed, the way it looks now is not really great, I tried to fix it in the last commit so let me know after you tested it a bit.

**Comment by omarelmalki** [comment]
> > Great job on the changes. A few bonus UI changes :
> > 
> > * In QRCodeShow activity, try to reduce the size of the large token and keep either its name or its id (content of the QRCode).
> 
> Thank you for your review ! Indeed, the way it looks now is not really great, I tried to fix it in the last commit so let me know after you tested it a bit.

Perfect, it looks better now !

**Pull request merged**
