### PR TITLE
Fix sign-in with Google bug 

### PR DESCRIPTION
**Pull request by omarelmalki**
Some of you have reported a bug when signing-in with google (activity not changing).
It always worked locally for me and passed the tests but apparently it does not work on other devices and emulators.

To fix this, you must add your SHA-1 fingerprint in Firebase by following the tutorial in this [wiki page](https://github.com/BrugApp/brug/wiki/Add-your-SHA-1-fingerprint-in-the-Firebase-unlost-project).

### CODE REVIEW

**Review by ha2san — APPROVED** [review]
Nice fix, it works for me

**Comment by pmcintyr** [comment]
Looks good, I added my fingerprint and the sign-in seems to work for me👍

**Review by pmcintyr — APPROVED** [review]
Looks good, I had some [trouble with the SHA-1](https://stackoverflow.com/questions/12214467/how-to-obtain-signing-certificate-fingerprint-sha1-for-oauth-2-0-on-android/21596198#21596198) but now I added my fingerprint and the sign-in works for me👍

**Comment by omarelmalki** [comment]
> Looks good, I had some [trouble with the SHA-1](https://stackoverflow.com/questions/12214467/how-to-obtain-signing-certificate-fingerprint-sha1-for-oauth-2-0-on-android/21596198#21596198) but now I added my fingerprint and the sign-in works for me👍

Nice, I will try to improve the wiki accordingly.

**Pull request merged**
